### ISSUE TITLE
[BUG] `Type 'ReactNativePlugin' is not assignable to type 'ITelemetryPlugin'.`

### ISSUE THREAD

**Issue by stefan-schweiger** [microsoft/applicationinsights-react-native#26]
**Description**
Same as this issue https://github.com/microsoft/applicationinsights-react-js/issues/32

Tried with the following versions:

- @microsoft/applicationinsights-react-native v3.0.3
- @microsoft/applicationinsights-web v3.0.2

and

- @microsoft/applicationinsights-react-native v4.0.0-nightly.2306-02
- @microsoft/applicationinsights-web v3.0.3-nightly3.2306-01

**Steps to Reproduce**

```
import { ApplicationInsights } from '@microsoft/applicationinsights-web';
import { ReactNativePlugin } from '@microsoft/applicationinsights-react-native';

var RNPlugin = new ReactNativePlugin();
var appInsights = new ApplicationInsights({
    config: {
        instrumentationKey: 'YOUR_INSTRUMENTATION_KEY_GOES_HERE',
        extensions: [RNPlugin]
    }
});
appInsights.loadAppInsights();
```

**Comment by MSNev** [comment]
We have not yet released a compatible version of this component to fully support v3 of Application Insights
https://github.com/microsoft/applicationinsights-react-native#compatibility-matrix

As part of the release we will be renumbering to match the major number of the supported react framework
